use_frameworks!

platform :ios, '8.0'

target 'yyCocoapodsTest01_Example' do
  pod 'yyCocoapodsTest01', :path => '../'

  target 'yyCocoapodsTest01_Tests' do
    inherit! :search_paths

    
  end
end
